IO2-44 Add user
Shaveek23/SystemPromocjiRepo pull request #25
Opened 2021-04-19 00:05 UTC by Gawezi

2021-04-19 08:36 UTC, Shaveek23 requested changes

2021-04-19 08:36 UTC, Shaveek23 commented on WebApi/WebApi/Controllers/UserController.cs
> +        }
Dlaczego tylko jedna metoda ma [FromHeader] ? Czy na pewno się zgadza z dokumentacją?
Poza tym jezeli dodajesz [FromHeader] to musisz dodać [Required] czyli:
[Required][FromHeader]

2021-04-19 08:36 UTC, Shaveek23 commented on WebApi/WebApi/Models/DTO/UserDTO.cs
> +            if (UserName == "" || UserEmail == null)
ta metoda nie ma sensu bo jeżeli w powyższym mamy te atrybuty z minLength i z EmailAddress to ten warunek z ifa nigdy nie będzie prawdą

2021-04-19 08:36 UTC, Shaveek23 commented on WebApi/WebApi/Services/Serives Implementations/UserService.cs
> +        }
czy mapper w tych dwóch przypadkach na pewno zwraca nulla , po tym jak go dostaje?

2021-04-19 08:36 UTC, Shaveek23 commented on WebApi/WebApi/Services/Services Implementations/UserService.cs
> +{
co to za błędy? jakieś konflikty nazw 
NAPRAWIĆ

2021-04-19 08:36 UTC, Shaveek23 commented on WebApi/WebApi/Controllers/UserController.cs
> +    {
dlaczego nie ma edycji użytkownika i usuwania?

2021-04-20 12:04 UTC, Gawezi commented on WebApi/WebApi/Controllers/UserController.cs
> +    {
Są niżej

2021-04-21 15:05 UTC, closed without merging