IO2-44 Add categories resource
Shaveek23/SystemPromocjiRepo pull request #26
Opened 2021-04-19 00:05 UTC by Gawezi

2021-04-19 08:26 UTC, Shaveek23 requested changes

2021-04-19 08:26 UTC, Shaveek23 commented on WebApi/WebApi/Database/DatabaseContext.cs
> +                modelBuilder.Entity<Category>().Property(p => p.Name).IsRequired().HasMaxLength(50);
MinLength może tez ? chyba nie chcemy kategorii z pustym stringiem

2021-04-19 08:26 UTC, Shaveek23 commented on WebApi/WebApi/Models/DTO/CategoryDTO.cs
> +        [MaxLength(50)]
dodać atrybut
[Required] wszędzie gdzie wymagamy aby dane pole było konieczne (czyli chyba wszędzie)

2021-04-19 08:26 UTC, Shaveek23 commented on WebApi/WebApi/Services/Services Implementations/CategoryService.cs
> +        }
zobacz że metody z Repository<T> w momencie failure zwracają ServiceResult z wartością domyślną jako Result (dla klass null, dla int? też null, dla bool false) dlatego czy na pewno Mapper obsługuje sytuację że dostaje nulla? Powinien wtedy też zwracać null

2021-04-19 08:26 UTC, Shaveek23 commented on WebApi/WebApi/Services/Services Implementations/CategoryService.cs
> +        }
j. w.

2021-04-19 08:28 UTC, Shaveek23 requested changes

2021-04-19 08:28 UTC, Shaveek23 commented on WebApi/WebApi/Controllers/CategoryController.cs
> +        {
gdzie są [Required][FromHeader] ? Czy w dokumentacji one są wymagane tutaj?

2021-04-20 11:14 UTC, Gawezi commented on WebApi/WebApi/Database/DatabaseContext.cs
> +                modelBuilder.Entity<Category>().Property(p => p.Name).IsRequired().HasMaxLength(50);
Nie widzę opcji ustawienia MinLength. W CategoryDTO jest ustawione MinLength wiec nie pozwoli na pustego stringa

2021-04-20 15:57 UTC, closed without merging