Resources/user
Shaveek23/SystemPromocjiRepo pull request #29
Opened 2021-04-21 20:45 UTC by Virus887

I create pull request because Konrad can't do it now. Take a look on it.

2021-04-22 09:37 UTC, Shaveek23 requested changes

2021-04-22 09:37 UTC, Shaveek23 commented on WebApi/WebApi/Models/DTO/UserDTO.cs
> +        public bool Active { get; set; }
Dlaczego przy polach nie ma [Required] ? powinny być nullable i być [Required], uwaga testy w mapperze się mogą wysypać przy zmianie na nullable, musisz naprawić

2021-04-22 09:37 UTC, Shaveek23 commented on WebApi/WebApi/Models/DTO/UserDTO.cs
> +        public bool Active { get; set; }
niezgodność z dokumentacją - pole powinno się nazywać isActive

2021-04-22 09:37 UTC, Shaveek23 commented on WebApi/WebApi/Controllers/UserController.cs
> +
Niezgodność z dokumentacją - brak headerów [Required][FromHeader] w metodach post, put, delete

2021-04-23 13:46 UTC, Gawezi commented on WebApi/WebApi/Models/DTO/UserDTO.cs
> +        public bool Active { get; set; }
W bazie danych dołączonej do projektu jest Active

2021-04-23 16:09 UTC, merged