Resources/categories
Shaveek23/SystemPromocjiRepo pull request #30
Opened 2021-04-21 20:46 UTC by Virus887

I create pull request because Konrad can't do it now. Take a look on it.

2021-04-21 21:01 UTC, Virus887 reviewed
Ogólnie wydaje się być wszystko spoko. Jedyne na co zwróciłbym uwagę to nie pisanie w testach rzeczy typu xd, lol, kupa itp. Nic nas to nie kosztuje a ProductOwnera, który przegląda te testy może drażnić :)

2021-04-22 09:44 UTC, Shaveek23 requested changes

2021-04-22 09:44 UTC, Shaveek23 commented on WebApi/WebApi/Models/DTO/CategoryDTO.cs
> +        public int CategoryID { get; set; }
jeżeli ten int nie jest nullable to [Required] nie dziala -> musi być nullable, pamietaj o naprawieniu testów w mapperrze które sie wysypia przez to

2021-04-23 13:43 UTC, Gawezi approved these changes

2021-04-23 13:44 UTC, Gawezi commented
Zmiany wprowadzone

2021-04-23 16:05 UTC, Shaveek23 approved these changes

2021-04-23 16:06 UTC, merged